# Site settings
title: ZATA
email: taylorzr@gmail.com  
description: "A weird kid's blog about the devbootcamp experience covering technical aspects of ruby, javascript, css, and html, and the corresponding emotional battles of working, learning and starting a family all at the same time."
baseurl: ""
url: "taylorzr.github.io"
twitter_username: zata42
github_username:  taylorzr

# Build settings
markdown: kramdown
permalink: pretty
